spring.application.name=exam

client.timeout.connect=10
client.timeout.read=30

client.petstore.createPet.url=https://petstore.swagger.io/v2/pet
client.petstore.retrievePet.url=https://petstore.swagger.io/v2/pet/{idPet}

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
